export const ACLNG: string
export const AUTH: string
export const BUSY: string
export const CLNG: string
export const ERR: string
export const IGME: string
export const GST: string
export const MOVE: string
export const NOPLR: string
export const NOSCP: string
export const READY: string
export const SINF: string
export const SUB: string
export const SRNDR: string
export const TELL: string
export const OUCNT: string
export const UNSUB: string
export const XCLNG: string
