export const AUTH='authenticate'
export const ERR='error'
export const NOPLR='no_player'
export const SUB='subscribe_universe_callback'
export const TELL='tell'
export const OUCNT='count_online_users'
export const USUB='unsubscribe_universe_callback'
